### ISSUE TITLE
Is there a paper introducing your project？

### ISSUE THREAD

**Issue by usutdzxych** [AlanSavio25/DeepSingleImageCalibration#1]
Your work is very good. Is there a paper introducing your project.

**Comment by AlanSavio25** [comment]
> Your work is very good. Is there a paper introducing your project.

Thanks! This project is the result of a Semester Thesis at ETH Zürich. I have a project report that I can share with you this week

**Comment by usutdzxych** [comment]
If so, I would greatly appreciate it

**Comment by usutdzxych** [comment]
> > 你的工作非常好。有没有一篇介绍你的项目的论文。
> 
> 谢谢！该项目是苏黎世联邦理工学院学期论文的结果。我有一份项目报告，本周可以与您分享

If so, I would greatly appreciate it

**Comment by AlanSavio25** [comment]
[Here is a link](https://drive.google.com/file/d/1cEFN1oRmT08Sysqz4idrk84Aww7Q5Swj/view?usp=share_link) to my project report. If you have any questions, please feel free to ask!
