### ISSUE TITLE
error:

### ISSUE THREAD

**Issue by usutdzxych** [AlanSavio25/DeepSingleImageCalibration#2]
ModuleNotFoundError: No module named 'calib.calib.datasets.calibration_dataset'

**Comment by AlanSavio25** [comment]
> ModuleNotFoundError: No module named 'calib.calib.datasets.calibration_dataset'

I'm still in the process of pushing all the code and cleaning the repository (should be ready by the end of next week). The calibration_dataset module (dataset class for loading training data - in our case SUN360) will be pushed soon, but note that you won't need this module if you are only running inference (you instead need calib.calib.datasets.external_dataset). You can safely comment out the 'import calib.calib.datasets.calibration_dataset' line for now
