### ISSUE TITLE
*** Aborted at 1710316103 (unix time) try "date -d @1710316103" if you are using GNU date ***

### ISSUE THREAD

**Issue by Alex000821** [AlanSavio25/DeepSingleImageCalibration#3]
Hello, I want to know if the network can run in Windows 11, I have an error after running：
*** Aborted at 1710316103 (unix time) try "date -d @1710316103" if you are using GNU date ***
    @     0x7ff97fbb4090 log2f
    @     0x7ff6e9a02698 OPENSSL_Applink
    @     0x7ff975f1e390 __C_specific_handler
    @     0x7ff98265441f __chkstk
    @     0x7ff9825ce466 RtlFindCharInUnicodeString
    @     0x7ff98265340e KiUserExceptionDispatcher
    @     0x7ff92f1126de void __cdecl __ExceptionPtrRethrow(void const * __ptr64)
    @     0x7ff90d2b45be void __cdecl std::rethrow_exception(class std::exception_ptr)
    @     0x7ff90d2b6317 void __cdecl pybind11::detail::translate_local_exception(class std::exception_ptr)
    @     0x7ff9014fd6a5 (unknown)
    @     0x7ff901a2f9e9 PyInit_pycolmap
    @     0x7ff9536a1080 (unknown)
    @     0x7ff9536a26a5 __NLG_Return2
    @     0x7ff982653c66 RtlCaptureContext2
    @     0x7ff901500194 (unknown)
    @     0x7ff912ec6f60 _PyMethodDef_RawFastCallKeywords
    @     0x7ff912ec5f26 _PyObject_MakeTpCall
    @     0x7ff912ed266b PyWrapper_New
    @     0x7ff912f0e34a _PyObject_GenericGetAttrWithDict
    @     0x7ff912f0d939 PyObject_GetAttrString
    @     0x7ff90153575e PyInit_pycolmap
    @     0x7ff90158d9d6 PyInit_pycolmap
    @     0x7ff901567384 PyInit_pycolmap
    @     0x7ff901524842 (unknown)
    @     0x7ff901530a07 PyInit_pycolmap
    @     0x7ff9015302fe PyInit_pycolmap
    @     0x7ff912fd21cd PyImport_AppendInittab
    @     0x7ff912fd1896 PyImport_Import
    @     0x7ff912f094b5 _PyCFunction_DebugMallocStats
    @     0x7ff912ec606e PyVectorcall_Call
    @     0x7ff912fa3a20 PyEval_GetFuncDesc
    @     0x7ff912fa0571 _PyEval_EvalFrameDefault

**Comment by AlanSavio25** [comment]
Hi Alex, we only tested our code on Linux, but it seems like you don't have all the required libraries installed correctly

**Comment by sarlinpe** [comment]
This is a problem with pycolmap, not with this repo. We'd need to know which version you installed and how (pypi, source).

**Comment by Alex000821** [comment]
> This is a problem with pycolmap, not with this repo. We'd need to know which version you installed and how (pypi, source).

Yes, it's a question about pycolmap, and I'm at this URL: https://github.com/3DOM-FBK/deep-image-matching/issues/35 read that pycolmap for windows seems to have a bug, so I have ubuntu installed to run it now

**Comment by Alex000821** [comment]
But when I run it in Ubuntu, I get the error: 'Pycolmap. Camera' object has no attribute 'image_to_world', my pycolmap version is 0.6.1

**Comment by sarlinpe** [comment]
The function has been renamed `cam_from_img` from v0.5.0 onwards https://github.com/colmap/pycolmap/releases/tag/v0.5.0 This repository was developed for v0.4.0.

**Comment by Alex000821** [comment]
Now I am running in the environment of pycolmap0.4.0, but it seems that there are still some problems. My skill is really limited, and I would like to ask for your help. After I ran python -m calib.calib.run --img_dir images/, my Testing: 0% progress didn't increase and there were other errors:
/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/cuda/__init__.py:141: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11080). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
[03/14/2024 21:26:23 calib INFO] Starting test weights
[03/14/2024 21:26:23 calib.calib.datasets.base_dataset INFO] Creating dataset ExternalDataset
Testing:   0%|                                                                                    | 0/1 [00:00<?, ?it/s]/root/DeepSingleImageCalibration/calib/calib/datasets/base_dataset.py:56: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = elem.storage()._new_shared(numel)
Testing:   0%|                                                                                    | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/pytorch/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/DeepSingleImageCalibration/calib/calib/run.py", line 121, in <module>
    main()
  File "/root/DeepSingleImageCalibration/calib/calib/run.py", line 109, in main
    plt = plot_row([{**{k: output[k].unsqueeze(0).cpu().item()
  File "/root/DeepSingleImageCalibration/calib/calib/datasets/viz_2d.py", line 156, in plot_row
    cv2.line(im, (pred_x2, pred_y2),
cv2.error: OpenCV(4.9.0) :-1: error: (-5:Bad argument) in function 'line'
> Overload resolution failed:
>  - Layout of the output array img is incompatible with cv::Mat
>  - Expected Ptr<cv::UMat> for argument 'img'

**Comment by Alex000821** [comment]
> Hi Alex, we only tested our code on Linux, but it seems like you don't have all the required libraries installed correctly

hi,Why is the progress bar of testing 0 after I run it?
(pytorch) root@staffgod:~/DeepSingleImageCalibration# python -m calib.calib.run --img_dir images/
/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/cuda/__init__.py:141: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11080). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
[03/14/2024 21:26:23 calib INFO] Starting test weights
[03/14/2024 21:26:23 calib.calib.datasets.base_dataset INFO] Creating dataset ExternalDataset
Testing:   0%|                                                                                    | 0/1 [00:00<?, ?it/s]/root/DeepSingleImageCalibration/calib/calib/datasets/base_dataset.py:56: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = elem.storage()._new_shared(numel)
Testing:   0%|                                                                                    | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/pytorch/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/DeepSingleImageCalibration/calib/calib/run.py", line 121, in <module>
    main()
  File "/root/DeepSingleImageCalibration/calib/calib/run.py", line 109, in main
    plt = plot_row([{**{k: output[k].unsqueeze(0).cpu().item()
  File "/root/DeepSingleImageCalibration/calib/calib/datasets/viz_2d.py", line 156, in plot_row
    cv2.line(im, (pred_x2, pred_y2),
cv2.error: OpenCV(4.9.0) :-1: error: (-5:Bad argument) in function 'line'
> Overload resolution failed:
>  - Layout of the output array img is incompatible with cv::Mat
>  - Expected Ptr<cv::UMat> for argument 'img'

**Comment by Alex000821** [comment]
It is about some grammar problems of cv, I finally solved it, and it can run, thank you for your help!
